version: 2

project_name: aqc

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X main.version={{.Version}}"

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: amantham20
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - repository:
      owner: amantham20
      name: homebrew-aqc
    description: "AQC - A powerful CLI tool for data processing"
    homepage: "https://github.com/amantham20/aqc"
    test: ./aqc --version

snapcrafts:
  - name: aqc
    summary: "AQC CLI"
    description: "A powerful CLI for data processing"
    base: core22
    grade: stable
    confinement: strict

chocolateys:
  - name: aqc
    description: "AQC - A powerful CLI for data processing"
    authors: ["Amantham20"]
    title: "AQC"

nfpms:
  - package_name: aqc
    homepage: "https://github.com/amantham20/aqc"
    description: "A powerful CLI tool written in Go for data processing"
    maintainer: "Aman Dhruva Thamminana <thammina@msu.edu>"
    license: MIT
    formats:
      - deb
      - rpm

dockers:
  - image_templates:
      - "ghcr.io/amantham20/aqc:{{ .Version }}"
    dockerfile: Dockerfile
